//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussianTasks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RussianTasks.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите завершить упражнение?.
        /// </summary>
        internal static string accent_exercise_exit_message {
            get {
                return ResourceManager.GetString("accent_exercise_exit_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить упражнение.
        /// </summary>
        internal static string accent_exercise_exit_title {
            get {
                return ResourceManager.GetString("accent_exercise_exit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Существительные.
        /// </summary>
        internal static string accents_section_name_1 {
            get {
                return ResourceManager.GetString("accents_section_name_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мой словарь.
        /// </summary>
        internal static string accents_section_name_101 {
            get {
                return ResourceManager.GetString("accents_section_name_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неподвижное ударение.
        /// </summary>
        internal static string accents_section_name_2 {
            get {
                return ResourceManager.GetString("accents_section_name_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Глаголы.
        /// </summary>
        internal static string accents_section_name_3 {
            get {
                return ResourceManager.GetString("accents_section_name_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прилагательные.
        /// </summary>
        internal static string accents_section_name_4 {
            get {
                return ResourceManager.GetString("accents_section_name_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причастия.
        /// </summary>
        internal static string accents_section_name_5 {
            get {
                return ResourceManager.GetString("accents_section_name_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деепричастия.
        /// </summary>
        internal static string accents_section_name_6 {
            get {
                return ResourceManager.GetString("accents_section_name_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наречия.
        /// </summary>
        internal static string accents_section_name_7 {
            get {
                return ResourceManager.GetString("accents_section_name_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта программа была активирована для другого устройства.
        /// </summary>
        internal static string activation_error_activated_on_another_machine {
            get {
                return ResourceManager.GetString("activation_error_activated_on_another_machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидный ключ.
        /// </summary>
        internal static string activation_error_invalid_key {
            get {
                return ResourceManager.GetString("activation_error_invalid_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этот ключ уже использован на другом устройстве.
        /// </summary>
        internal static string activation_error_key_is_already_used {
            get {
                return ResourceManager.GetString("activation_error_key_is_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для активации программы необходимо соединение с Интернетом.
        /// </summary>
        internal static string activation_error_no_internet_connection {
            get {
                return ResourceManager.GetString("activation_error_no_internet_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при обращении к серверу активации.
        /// </summary>
        internal static string activation_error_server_problem {
            get {
                return ResourceManager.GetString("activation_error_server_problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        internal static string activation_window_button_text {
            get {
                return ResourceManager.GetString("activation_window_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя пользователя и ключ.
        /// </summary>
        internal static string activation_window_enter_key_message {
            get {
                return ResourceManager.GetString("activation_window_enter_key_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        internal static string activation_window_field_1 {
            get {
                return ResourceManager.GetString("activation_window_field_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ активации.
        /// </summary>
        internal static string activation_window_field_2 {
            get {
                return ResourceManager.GetString("activation_window_field_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа успешно активирована!.
        /// </summary>
        internal static string activation_window_success {
            get {
                return ResourceManager.GetString("activation_window_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активация программы.
        /// </summary>
        internal static string activation_window_title {
            get {
                return ResourceManager.GetString("activation_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, подождите.
        /// </summary>
        internal static string activation_window_wait_message {
            get {
                return ResourceManager.GetString("activation_window_wait_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string back_text {
            get {
                return ResourceManager.GetString("back_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string button_ok_text {
            get {
                return ResourceManager.GetString("button_ok_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string cancel_text {
            get {
                return ResourceManager.GetString("cancel_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный ключ доступа.
        /// </summary>
        internal static string editor_access_window_error_invalid_key {
            get {
                return ResourceManager.GetString("editor_access_window_error_invalid_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите ключ доступа к редактору.
        /// </summary>
        internal static string editor_access_window_message {
            get {
                return ResourceManager.GetString("editor_access_window_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступ к редактору упражнений.
        /// </summary>
        internal static string editor_access_window_title {
            get {
                return ResourceManager.GetString("editor_access_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден файл заданий.
        /// </summary>
        internal static string error_cannot_find_config_file {
            get {
                return ResourceManager.GetString("error_cannot_find_config_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден файл заданий {0}.
        /// </summary>
        internal static string error_cannot_find_config_file_with_name {
            get {
                return ResourceManager.GetString("error_cannot_find_config_file_with_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В вашем словаре пока еще нет слов!.
        /// </summary>
        internal static string error_no_words_in_vocabulary {
            get {
                return ResourceManager.GetString("error_no_words_in_vocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string error_text {
            get {
                return ResourceManager.GetString("error_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактор упражнений.
        /// </summary>
        internal static string exercise_editor_title {
            get {
                return ResourceManager.GetString("exercise_editor_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ударения в словах (№4).
        /// </summary>
        internal static string exercise_name_accents {
            get {
                return ResourceManager.GetString("exercise_name_accents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слитное/раздельное написание.
        /// </summary>
        internal static string exercise_name_repeating {
            get {
                return ResourceManager.GetString("exercise_name_repeating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Орфография.
        /// </summary>
        internal static string exercise_name_spelling {
            get {
                return ResourceManager.GetString("exercise_name_spelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грамматические нормы.
        /// </summary>
        internal static string exercise_name_variant {
            get {
                return ResourceManager.GetString("exercise_name_variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответить.
        /// </summary>
        internal static string exercise_window_button_answer {
            get {
                return ResourceManager.GetString("exercise_window_button_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Далее.
        /// </summary>
        internal static string exercise_window_button_continue {
            get {
                return ResourceManager.GetString("exercise_window_button_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты.
        /// </summary>
        internal static string exercise_window_button_finish {
            get {
                return ResourceManager.GetString("exercise_window_button_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропустить.
        /// </summary>
        internal static string exercise_window_button_skip {
            get {
                return ResourceManager.GetString("exercise_window_button_skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прогресс: {0}/{1}.
        /// </summary>
        internal static string exercise_window_progress_label_template {
            get {
                return ResourceManager.GetString("exercise_window_progress_label_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string exit_app_cancel_button {
            get {
                return ResourceManager.GetString("exit_app_cancel_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить.
        /// </summary>
        internal static string exit_app_exit_button {
            get {
                return ResourceManager.GetString("exit_app_exit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите завершить работу с программой?.
        /// </summary>
        internal static string exit_app_message {
            get {
                return ResourceManager.GetString("exit_app_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход из программы.
        /// </summary>
        internal static string exit_app_tittle {
            get {
                return ResourceManager.GetString("exit_app_tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить.
        /// </summary>
        internal static string finish_exercise_text {
            get {
                return ResourceManager.GetString("finish_exercise_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить в мой словарь.
        /// </summary>
        internal static string hint_add_to_my_vocabulary {
            get {
                return ResourceManager.GetString("hint_add_to_my_vocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убрать из моего словаря.
        /// </summary>
        internal static string hint_remove_from_my_vocabulary {
            get {
                return ResourceManager.GetString("hint_remove_from_my_vocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые упражнения будут доступны\r\nв следующих версиях.
        /// </summary>
        internal static string next_version_adv {
            get {
                return ResourceManager.GetString("next_version_adv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Репетитор Ксения Куликова.
        /// </summary>
        internal static string preloader_copyright_text {
            get {
                return ResourceManager.GetString("preloader_copyright_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подготовка к ЕГЭ\r\nпо русскому языку.
        /// </summary>
        internal static string preloader_title {
            get {
                return ResourceManager.GetString("preloader_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №12 (НЕ/НИ слитно и раздельно).
        /// </summary>
        internal static string repeating_section_name_1 {
            get {
                return ResourceManager.GetString("repeating_section_name_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №13 (слитно/раздельно/дефис).
        /// </summary>
        internal static string repeating_section_name_2 {
            get {
                return ResourceManager.GetString("repeating_section_name_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всё подряд.
        /// </summary>
        internal static string section_name_shuffle {
            get {
                return ResourceManager.GetString("section_name_shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мой словарь.
        /// </summary>
        internal static string section_name_vocabulary {
            get {
                return ResourceManager.GetString("section_name_vocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string select_section_window_button_back {
            get {
                return ResourceManager.GetString("select_section_window_button_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Части речи.
        /// </summary>
        internal static string select_section_window_title_accents {
            get {
                return ResourceManager.GetString("select_section_window_title_accents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите раздел.
        /// </summary>
        internal static string select_section_window_title_default {
            get {
                return ResourceManager.GetString("select_section_window_title_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №8 (гласные в корне).
        /// </summary>
        internal static string spelling_section_name_1 {
            get {
                return ResourceManager.GetString("spelling_section_name_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №9 (приставки слов).
        /// </summary>
        internal static string spelling_section_name_2 {
            get {
                return ResourceManager.GetString("spelling_section_name_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №10 (суффиксы слов).
        /// </summary>
        internal static string spelling_section_name_3 {
            get {
                return ResourceManager.GetString("spelling_section_name_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №11 (глаголы и причастия).
        /// </summary>
        internal static string spelling_section_name_4 {
            get {
                return ResourceManager.GetString("spelling_section_name_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №14 (Н и НН в словах).
        /// </summary>
        internal static string spelling_section_name_5 {
            get {
                return ResourceManager.GetString("spelling_section_name_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите задание из списка:.
        /// </summary>
        internal static string tasks_window_message {
            get {
                return ResourceManager.GetString("tasks_window_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список упражнений.
        /// </summary>
        internal static string tasks_window_title {
            get {
                return ResourceManager.GetString("tasks_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string update_application_window_button_cancel {
            get {
                return ResourceManager.GetString("update_application_window_button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string update_application_window_button_update {
            get {
                return ResourceManager.GetString("update_application_window_button_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string update_application_window_error_button_cancel {
            get {
                return ResourceManager.GetString("update_application_window_error_button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторить.
        /// </summary>
        internal static string update_application_window_error_button_retry {
            get {
                return ResourceManager.GetString("update_application_window_error_button_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При загрузке обновления произошла ошибка.
        /// </summary>
        internal static string update_application_window_error_message {
            get {
                return ResourceManager.GetString("update_application_window_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание.
        /// </summary>
        internal static string update_application_window_error_title {
            get {
                return ResourceManager.GetString("update_application_window_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступно обновление программы до версии v{0} (текущая версия v{1}). Скачать обновление?.
        /// </summary>
        internal static string update_application_window_message {
            get {
                return ResourceManager.GetString("update_application_window_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание.
        /// </summary>
        internal static string update_application_window_title {
            get {
                return ResourceManager.GetString("update_application_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правильная форма слова.
        /// </summary>
        internal static string variant_section_name_1 {
            get {
                return ResourceManager.GetString("variant_section_name_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паронимы.
        /// </summary>
        internal static string variant_section_name_2 {
            get {
                return ResourceManager.GetString("variant_section_name_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать.
        /// </summary>
        internal static string voc_window_button_print {
            get {
                return ResourceManager.GetString("voc_window_button_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прорешать.
        /// </summary>
        internal static string voc_window_button_study {
            get {
                return ResourceManager.GetString("voc_window_button_study", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавляйте сюда слова, вызывающие у Вас затруднения.
        /// </summary>
        internal static string vocabulary_hint {
            get {
                return ResourceManager.GetString("vocabulary_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите распечатать содержимое словаря или сохранить в файл?.
        /// </summary>
        internal static string vocabulary_print_alert_message {
            get {
                return ResourceManager.GetString("vocabulary_print_alert_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать.
        /// </summary>
        internal static string vocabulary_print_alert_print_text {
            get {
                return ResourceManager.GetString("vocabulary_print_alert_print_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить в файл.
        /// </summary>
        internal static string vocabulary_print_alert_save_text {
            get {
                return ResourceManager.GetString("vocabulary_print_alert_save_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать моего словаря.
        /// </summary>
        internal static string vocabulary_print_alert_title {
            get {
                return ResourceManager.GetString("vocabulary_print_alert_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите убрать слово &quot;{0}&quot; из словаря?.
        /// </summary>
        internal static string vocabulary_remove_word_text {
            get {
                return ResourceManager.GetString("vocabulary_remove_word_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убрать слово из моего словаря.
        /// </summary>
        internal static string vocabulary_remove_word_title {
            get {
                return ResourceManager.GetString("vocabulary_remove_word_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мой словарь.
        /// </summary>
        internal static string window_title_vocabulary {
            get {
                return ResourceManager.GetString("window_title_vocabulary", resourceCulture);
            }
        }
    }
}
